generic_stretch_blit: fix compilation due to undefined reference to DSPF_ARGBF88871
../../../../DirectFB/src/gfx/generic/generic_stretch_blit.c: In function 'stretch_hvx':
../../../../DirectFB/src/gfx/generic/generic_stretch_blit.c:444:21: error: 'DSPF_ARGBF88871' undeclared (first use in this function)
../../../../DirectFB/src/gfx/generic/generic_stretch_blit.c:444:21: note: each undeclared identifier is reported only once for each function it appears in