build: fix out of tree builds
---snip---
  CXX    util.lo
../../../src/gfx/util.cpp:46:30: fatal error: core/CoreSurface.h: No such file or directory
compilation terminated.
---snap---

The file in question is autogenerated and ends up below $(top_builddir), so this has
to be part of the included directories.